version: "3.1"

services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ai-models:/app/models
      - ai-data:/app/data
    ports:
      - "8157:8000"
    container_name: ai

volumes:
  ai-models:
  ai-data:
