{
 "title": "CO2 Emissions",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Year", "label": "Year" }
  ]
 },
 "panels": [
  { "title": "Population", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Population by 2030",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"populationPredicted\" FROM \"PopulationBy\" WHERE year = 2030"
    }
   ]
  },
  {
   "title": "Population by 2050",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"populationPredicted\" FROM \"PopulationBy\" WHERE year = 2050"
    }
   ]
  },
  {
   "title": "Population Increase From Now to 2030 (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"calculatedPopulationGrowthPercent\" FROM \"PopulationBy\" WHERE year = 2030 "
    }
   ]
  },
  {
   "title": "Population Increase From Now to 2050 (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"calculatedPopulationGrowthPercent\" FROM \"PopulationBy\" WHERE year = 2050 "
    }
   ]
  },
  {
   "title": "Population",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT population AS \"Population\", \"time\" AS \"time\" FROM \"Population\""
    },
    {
     "rawSql": "SELECT \"populationPredicted\" AS \"Population (Predicted)\", \"time\" AS \"time\" FROM \"Population\""
    }
   ]
  },
  {
   "title": "Population by The End of The Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"endOfYearPopulationPredicted\" AS \"Population by the end of the year\" FROM \"Population\" "
    }
   ]
  },
  {
   "title": "Population Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \"populationGrowthThisYear\" AS \"Population Growth\", \"time\" AS \"time\" FROM \"Population\""
    },
    {
     "rawSql": "SELECT \"populationGrowthThisYearPredicted\" AS \"Population Growth (Predicted)\", \"time\" AS \"time\" FROM \"Population\""
    }
   ]
  },
  {
   "title": "Population Growth by The End of The Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"endOfYearPopulationGrowthPredicted\" FROM \"Population\""
    }
   ]
  },
  { "title": "CO₂ Emissions ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total CO2 Emissions by 2030",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "gigatons" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"totalCo2EmissionsPredicted\"/10^9 FROM \"Co2EmissionsBy\" WHERE year = 2030"
    }
   ]
  },
  {
   "title": "Total CO2 Emissions by 2050",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "gigatons" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"totalCo2EmissionsPredicted\"/10^9 FROM \"Co2EmissionsBy\" WHERE year = 2050"
    }
   ]
  },
  {
   "title": "Temprature Anomaly by 2030",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"tempAnomalyPredicted\" FROM \"Co2EmissionsBy\" WHERE year = 2030"
    }
   ]
  },
  {
   "title": "Temprature Anomaly by 2050",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"tempAnomalyPredicted\" FROM \"Co2EmissionsBy\" WHERE year = 2050"
    }
   ]
  },
  {
   "title": "Current CO₂ Emissions This Year",
   "type": "xychart",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"currentCo2Emissions\" as \"CO₂ Emissions\", \"currentCo2EmissionsPredicted\" as \"Current CO₂ Emissions (Predicted)\", \"populationGrowthThisYear\" as \"Population Growth This Year\" FROM \"AnnualCo2Emissions\""
    }
   ]
  },
  {
   "title": "Predicted Annual CO₂ Emissions This Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "gigatons" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"annualCo2EmissionsPredicted\"/10^9 FROM \"AnnualCo2Emissions\""
    }
   ]
  },
  {
   "title": "Total CO₂ emissions",
   "type": "trend",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"totalCo2EmissionsPredicted\"/10^9 AS \"Total CO₂ emissions (Gigatons)\", \"population\" AS \"Population\" FROM \"TotalCo2Emissions\" "
    }
   ]
  },
  {
   "title": "Predicted Total CO₂ Emitted by The End of This Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "gigatons" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"endOfYearTotalCo2EmissionsPredicted\"/10^9 FROM \"TotalCo2Emissions\""
    }
   ]
  },
  { "title": "Predictor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Population Predictor Precision",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"populationPrecision\" AS \"Precision\" FROM \"PredictorStats\""
    }
   ]
  },
  {
   "title": "Population Growth Predictor Precision",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"populationGrowthPrecision\" AS \"Precision\" FROM \"PredictorStats\""
    }
   ]
  }
 ]
}